name: "Job Complete"
description: "Notifies that the job was completed"
inputs:
  orchestrator:
    description: "URL of orchestrator repository"
    required: true
runs:
  using: "node16"
  main: "index.js"
